Define __inout empty for MinGW build
This fixes GCC compile errors: '__inout' has not been declared

The keyword is defined in include/driverspecs.h to an empty value and
has been adopted instead of using the include file.

This also fixes some other compile errors around __inout, e.g.:
../src/dpiManager.h:53:33: error: expected ',' or '...' before '*' token
../src/dpiManager.h:54:9: error: 'pRect' was not declared in this scope