- avoid build issue for unicode: 2>..\lexers\LexUser.cxx(1406): error C2664: 'void GenerateVector(vvstring &,const char *,char *,int)' : cannot convert argument 3 from 'const wchar_t [3]' to 'char *' 2>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast