Enable C++ 2014 support for the MinGW build
C++ 2011 is needed to fix this GCC compile error:

In file included from /usr/i686-w64-mingw32/include/c++/5.1.0/unordered_map:35:0,
                 from ../src/ScitillaComponent/UserDefineDialog.h:54,
                 from ../src/ScitillaComponent/ScintillaEditView.h:53,
                 from ../src/Notepad_plus.h:32,
                 from ../src/Notepad_plus.cpp:30:
/usr/i686-w64-mingw32/include/c++/5.1.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

C++ 2014 is needed to fix these GCC compile errors:

../src/ScitillaComponent/ScintillaEditView.cpp:1911:33: error: 'make_unique' is not a member of 'std'
  std::unique_ptr<TCHAR[]> buf = std::make_unique<TCHAR[]>(bufSize);
                                 ^
../src/ScitillaComponent/ScintillaEditView.cpp:1911:55: error: expected primary-expression before '[' token
  std::unique_ptr<TCHAR[]> buf = std::make_unique<TCHAR[]>(bufSize);
                                                       ^
../src/ScitillaComponent/ScintillaEditView.cpp:1911:56: error: expected primary-expression before ']' token
  std::unique_ptr<TCHAR[]> buf = std::make_unique<TCHAR[]>(bufSize);
                                                        ^