Add includes before shlobj.h to fix the MinGW build
Due to an upstream bug (MinGW-w64 5.1.0 used), which has been fixed on
2015-03-18:
http://sourceforge.net/p/mingw-w64/mingw-w64/ci/6c56d0b0eb5be9fbeb552ba070a2304b842a5102/

This fixes the following GCC compile errors:
/usr/i686-w64-mingw32/include/shlobj.h:37:3: error: 'EXTERN_C' does not name a type
   SHFOLDERAPI SHGetFolderPathW (HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath);
   ^