Reduce MinGW quirks for a current MinGW-w64 release (4.9.2)
_WIN32_IE is defined in include/sdkddkver.h:
In file included from /usr/i686-w64-mingw32/include/windows.h:10:0,
                 from ../src/MISC/Common/precompiledHeaders.h:60,
                 from ../src/Notepad_plus.cpp:29:
/usr/i686-w64-mingw32/include/sdkddkver.h:170:0: note: this is the location of the previous definition
 #define _WIN32_IE _WIN32_IE_IE60

_wtof() is available:
/usr/i686-w64-mingw32/include/stdlib.h:498:51: error: conflicting declaration of 'double _wtof(const wchar_t*)' with 'C' linkage
   _CRTIMP double __cdecl _wtof(const wchar_t *_Str);

eh.h is available, duplicated definition causes link error:
multiple definition of `_set_se_translator(void (*)(unsigned int, _EXCEPTION_POINTERS*))'

Also remove unused dummy defines.