Use _create_locale() instead of _wcreate_locale()
The wide-character version is not available in current MinGW-w64.
According to MSDN documentation the behaviour is identical, only the
locale parameter is an ordinary char type now.

This fixes the following GCC compile error:
../src/MISC/Common/Sorters.h: In constructor 'NumericSorter<T_Num>::NumericSorter(bool, size_t, size_t)':
../src/MISC/Common/Sorters.h:125:15: error: '::_wcreate_locale' has not been declared
   _usLocale = ::_wcreate_locale(LC_NUMERIC, TEXT("en-US"));
               ^